{{- if and .Values.redis.enabled (not .Values.redis.bitnami.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vigil.redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vigil.componentLabels" (dict "context" . "component" "redis") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
  selector:
    {{- include "vigil.componentSelectorLabels" (dict "context" . "component" "redis") | nindent 4 }}
{{- end }}
